moopy/moopy/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from accounts.views import login_view, register_view, logout_view

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('movies.urls')),
    url(r'^genres/', include('genres.urls')),
    url(r'^comments/', include('comments.urls')),
    url(r'^login/', login_view, name="login"),
    url(r'^logout/', logout_view, name="logout"),
    url(r'^register/', register_view, name="register"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

moopy/movies/urls.py
from django.conf.urls import url
from . import views

app_name = "movies"

urlpatterns = [
    url(r'^$', views.movie_list, name='movie_list'),
    url(r'^detail/(?P<slug>[\w-]+)/$', views.movie_detail, name='movie_detail'),
    url(r'^create/$', views.movie_create, name='movie_create'),
    url(r'^(?P<movie_id>\d+)/edit/$', views.movie_update, name='movie_update'),
    url(r'^(?P<movie_id>\d+)/delete/$', views.movie_delete, name='movie_delete'),
    url(r'^(?P<genre_id>\d+)/genre/$', views.movie_list_genre, name='movie_list_genre'),
]

moopy/templates/movie/movie_detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block head_title %}
{{ movie.title }} | {{ block.super }}
{% endblock head_title%}

{% block detail_link %}
<a href="{{ movie.get_absolute_url}}" class="header item">{{ movie.title }}</a>
{% endblock %}
{% block content %}
   <div class="ui segment">
       <div class="ui items">
              <div class="item">
                <div class="ui small image">
                    {% if movie.cover %}
                        <img src="{{ movie.cover.url }}">
                    {% endif %}
                </div>

                <div class="middle aligned content">
                  <div class="header">{{ movie.title }}  ({{ movie.year }})</div>
                  <div class="meta">
                    {% if movie.user.get_full_name %}
                      <span class="cinema">Author : <i>{{ movie.user.get_full_name }}</i> <br/></span>
                    {% endif %}
                  </div>
                  <div class="description">
                      <div class="preview-description">
                            {{ movie.get_markdown }}
                      </div>
                  </div>
                  <div class="extra">
                    <div class="ui label">{{ movie.genre }}</div>
                  </div>
                </div>
              </div>
        </div>
    </div>


   <div class="ui segment">
        <div class="ui embed" data-url="{{ movie.link_video }}" ></div>
   </div>

   <div class="ui segment">
       {% if request.user.is_authenticated %}
       <form class="ui form" method="POST" action="">{% csrf_token %}
           {{ comment_form | crispy }}
           <input type="submit" value="Post Comment"/>
       </form>
       {% else %}
       <p>You must login to comment</p>
       {% endif %}

       <hr />
       {% for comment in comments %}
        <p>{{ comment.message }}</p>
       <i>
           by : {{ comment.user }} on {{ comment.created | timesince }} ago |
           {% if comment.children.count > 0 %}
            {{ comment.children.count }} Comment{% if comment.children.count > 1 %}s{% endif %}
           {% endif %}
           <a class="comment-reply-button" href="#">Reply</a> |
           <a href="{{ comment.get_absolute_url }}">Thread</a>
       </i>
            <div class="comment-reply" style="display:none">
               {% for child_comment in comment.children %}
                    <p>{{ child_comment.message }}</p>
                    <i>by : {{ child_comment.user }} on {{ child_comment.created | timesince }} ago</i>
               {% endfor %}

                {% if request.user.is_authenticated %}
                <form class="ui form" method="POST" action="">{% csrf_token %}
                    {{ comment_form | crispy }}
                    <input type="hidden" name="parent_id" value="{{ comment.id }}"/>
                    <input type="submit" value="Reply"/>
                </form>
                {% else %}
                    <p>You must login to comment</p>
                {% endif %}
            </div>
       <br /><br /><br />
       {% endfor %}
   </div>

    <a href="{% url 'movies:movie_list' %}" class="fluid ui blue button">
        All Movies
    </a>

{% endblock %}

moopy/templates/movie/movie_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Movie Form{% endblock %}

{% block head_extra %}
    {{ form.media }}
{% endblock head_extra%}

{% block content %}
    <form class="ui form" method="POST" action="" enctype="multipart/form-data">{% csrf_token %}
        {{ form | crispy }}
        <input class="ui blue button" tabindex="0" type="submit" value="Save" />
        <div class="ui orange button" tabindex="0">Cancel</div>
    </form>

    <br/>
    <hr />
    <h2>Preview</h2>
    <div class="content-preview">
        <h3 id="preview-title"></h3>
        <p id="preview-description"></p>
    </div>
    <hr />
{% endblock %}

moopy/templates/movie/movie_list.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}
{{ title }} | {{ block.super}}
{% endblock %}

{% block content %}

    <div class="ui menu">
      <div class="item">
        <div class="ui action input">
            <form method="GET" action="">
              <input type="text" name="q" placeholder="Search" value="{{ request.get.q }}"/>
              <input class="ui blue button" type="submit" value="Go"/>
            </form>
        </div>
      </div>
      {% if request.user.is_staff or request.user.is_superuser %}
      <div class="right item">
            <a href="{% url 'movies:movie_create' %}" class="fluid ui blue button">New</a>
      </div>
      {% endif%}
    </div>

   {% for movie in all_movies %}
   <div class="ui segment">
   <div class="ui items">
          <div class="item">
            <div class="ui small image">
                {% if movie.cover %}
                    <img src="{{ movie.cover.url }}">
                {% endif %}
            </div>

            <div class="middle aligned content">
              <div class="header">{{ movie.title }}</div>

              <div class="description">
                  <p class="preview-description">
                    {{ movie.get_markdown | truncatechars:550 }}
                  </p>
              </div>

              <div class="extra">
                  {% if request.user.is_authenticated and request.user.is_staff or request.user.is_superuser %}
                    <a href="{% url 'movies:movie_update' movie.id %}" class="ui blue basic button">Edit</a>
                    <a href="{% url 'movies:movie_delete' movie.id %}" class="ui blue basic button">Delete</a>
                  {% endif %}
                    <a href="{{ movie.get_absolute_url }}" class="ui blue right floated basic button">Detail</a>
              </div>

            </div>

          </div>
    </div>
    </div>
   {% endfor %}

    <div class="ui pagination menu">
        {% if all_movies.has_previous %}
            <a class="active item" href="?{{ page_request_var }}={{ all_movies.previous_page_number }}
            {% if request.get.q %}&q={{ request.get.q }}{% endif %}">
                previous
            </a>
        {% endif %}
        <span class="item">
            Page {{ all_movies.number }} of {{ all_movies.paginator.num_pages }}.
        </span>
        {% if all_movies.has_next %}
            <a class="item" href="?{{ page_request_var }}={{ all_movies.next_page_number }}
            {% if request.get.q %}&q={{ request.get.q }}{% endif %}">
                next
            </a>
        {% endif %}
    </div>
{% endblock %}