moopy/genres/urls.py
from django.conf.urls import url
from . import views

app_name = "genres"

urlpatterns = [
    url(r'^$', views.genre_list, name='genre_list'),
    url(r'^detail/(?P<slug>[\w-]+)/$', views.genre_detail, name='genre_detail'),
    url(r'^create/$', views.genre_create, name='genre_create'),
    url(r'^(?P<genre_id>\d+)/edit/$', views.genre_update, name='genre_update'),
    url(r'^(?P<genre_id>\d+)/delete/$', views.genre_delete, name='genre_delete'),
]

moopy/moopy/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from accounts.views import login_view, register_view, logout_view

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('movies.urls')),
    url(r'^genres/', include('genres.urls')),
    url(r'^comments/', include('comments.urls')),
    url(r'^login/', login_view, name="login"),
    url(r'^logout/', logout_view, name="logout"),
    url(r'^register/', register_view, name="register"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

moopy/movies/urls.py
from django.conf.urls import url
from . import views

app_name = "movies"

urlpatterns = [
    url(r'^$', views.movie_list, name='movie_list'),
    url(r'^detail/(?P<slug>[\w-]+)/$', views.movie_detail, name='movie_detail'),
    url(r'^create/$', views.movie_create, name='movie_create'),
    url(r'^(?P<movie_id>\d+)/edit/$', views.movie_update, name='movie_update'),
    url(r'^(?P<movie_id>\d+)/delete/$', views.movie_delete, name='movie_delete'),
    url(r'^(?P<genre_id>\d+)/genre/$', views.movie_list_genre, name='movie_list_genre'),
]

moopy/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Standard Meta -->
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0" />
    <title>{% block title %}Home{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'semantic-ui/semantic.min.css' %}" />
    <link rel="stylesheet" href='{% static "css/base.css" %}'/>

    {% block head_extra %} {% endblock head_extra %}
</head>
<body>
    <div class="ui two column centered grid">
      <div class="column">
       <div class="ui inverted menu">
        <div class="ui container">
            <a href="{% url 'movies:movie_list' %}" class="header item">
                MooPy
            </a>
            {% block detail_link %}
            {% endblock %}
            <a href="{% url 'genres:genre_list' %}" class="header item">Genres</a>

          <div class="right menu">
             {% if not request.user.is_authenticated %}
                 <a href="{% url 'login' %}" class="header item">Login</a>
                 <a href="{% url 'register' %}" class="header item">Register</a>
             {% else %}
                 <a href="{% url 'logout' %}" class="header item">Logout</a>
             {% endif %}
          </div>
        </div>
       </div>

       <div class="ui main container">
           {% include "messages.html" %}
            {% block content %}
            {% endblock %}
       </div>

       <div class="ui inverted vertical footer segment">
        <div class="ui center aligned container">
          <div class="ui horizontal inverted small divided link list">
            <a class="item" href="#">Site Map</a>
            <a class="item" href="#">Contact Us</a>
            <a class="item" href="#">Terms and Conditions</a>
            <a class="item" href="#">Privacy Policy</a>
          </div>
        </div>
       </div>
       </div>

    </div>
    <script src="https://code.jquery.com/jquery-1.10.2.js"></script>
    <script src="{% static 'semantic-ui/semantic.min.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/marked/0.3.6/marked.min.js"></script>
    <script src="{% static 'js/base.js' %}"></script>
</body>
</html>

moopy/templates/messages.html
{% if messages %}

            {% for message in messages %}
            <div class="ui small message">
            {{ message }}
            </div>
            {% endfor %}

{% endif %}