moopy/genres/urls.py
from django.conf.urls import url
from . import views

app_name = "genres"

urlpatterns = [
    url(r'^$', views.genre_list, name='genre_list'),
    url(r'^detail/(?P<slug>[\w-]+)/$', views.genre_detail, name='genre_detail'),
    url(r'^create/$', views.genre_create, name='genre_create'),
    url(r'^(?P<genre_id>\d+)/edit/$', views.genre_update, name='genre_update'),
    url(r'^(?P<genre_id>\d+)/delete/$', views.genre_delete, name='genre_delete'),
]

moopy/moopy/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from accounts.views import login_view, register_view, logout_view

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('movies.urls')),
    url(r'^genres/', include('genres.urls')),
    url(r'^comments/', include('comments.urls')),
    url(r'^login/', login_view, name="login"),
    url(r'^logout/', logout_view, name="logout"),
    url(r'^register/', register_view, name="register"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

moopy/movies/urls.py
from django.conf.urls import url
from . import views

app_name = "movies"

urlpatterns = [
    url(r'^$', views.movie_list, name='movie_list'),
    url(r'^detail/(?P<slug>[\w-]+)/$', views.movie_detail, name='movie_detail'),
    url(r'^create/$', views.movie_create, name='movie_create'),
    url(r'^(?P<movie_id>\d+)/edit/$', views.movie_update, name='movie_update'),
    url(r'^(?P<movie_id>\d+)/delete/$', views.movie_delete, name='movie_delete'),
    url(r'^(?P<genre_id>\d+)/genre/$', views.movie_list_genre, name='movie_list_genre'),
]

moopy/genres/models.py
from django.db import models
from django.conf import settings
from django.core.urlresolvers import reverse
from django.db.models.signals import pre_save
from django.utils.text import slugify
from django.utils import timezone


class GenreManager(models.Manager):
    def active(self, *args, **kwargs):
        # Genre.objects.all() = super(GenreManager, self).all()
        return super(GenreManager, self).filter(draft=False).filter(publish__lte=timezone.now())


class Genre(models.Model):
    name = models.CharField(max_length=50)
    slug = models.SlugField(unique=True, blank=True)
    draft = models.BooleanField(default=False)
    publish = models.DateField(auto_now=False, auto_now_add=False, blank=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1)
    created = models.DateTimeField(auto_now=False, auto_now_add=True)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)

    objects = GenreManager()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("genres:genre_detail", kwargs={"slug": self.slug})


def create_genre_slug(instance, new_slug=None):
    slug = slugify(instance.name)
    if new_slug is not None:
        slug = new_slug
    qs = Genre.objects.filter(slug=slug).order_by("-id")
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" %(slug, qs.first().id)
        return create_genre_slug(instance, new_slug=new_slug)
    return slug


def pre_save_genre_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_genre_slug(instance)

pre_save.connect(pre_save_genre_receiver, sender=Genre)

moopy/genres/forms.py
from django import forms
from .models import Genre


class GenreForm(forms.ModelForm):
    class Meta:
        model = Genre
        fields = [
            "name",
            "draft",
            "publish"
        ]

moopy/genres/views.py
from django.contrib import messages
from django.http import HttpResponseRedirect, Http404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render, redirect, get_object_or_404
from .models import Genre
from .forms import GenreForm
from django.utils import timezone


def genre_list(request):
    today = timezone.now().date()
    genres = Genre.objects.active()
    if request.user.is_staff or request.user.is_superuser:
        genres = Genre.objects.all()

    query = request.GET.get("q")
    if query:
        genres = genres.filter(name__icontains=query)

    paginator = Paginator(genres, 5)

    page_request_var = "page"
    page = request.GET.get(page_request_var)

    try:
        all_genres = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        all_genres = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        all_genres = paginator.page(paginator.num_pages)

    context = {
        "all_genres" : all_genres,
        "title": "genre List",
        "page_request_var": page_request_var,
        "today": today,
    }
    return render(request, "genre/genre_list.html", context)


def genre_detail(request, slug= None):
    genre = get_object_or_404(Genre, slug=slug)
    if genre.publish > timezone.now().date() or genre.draft:
        if not request.user.is_staff or not request.user.is_superuser:
            raise Http404
    context = {
        "genre" : genre,
        "title" : genre.name
    }
    return render(request, "genre/genre_detail.html", context)


def genre_create(request):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404
    if not request.user.is_authenticated():
        raise Http404

    form = GenreForm(request.POST or None)
    if form.is_valid():
        genre = form.save(commit=False)
        genre.user = request.user
        genre.save()
    # if request.method  == "POST":
    #     name = request.POST.get("name")
    #     Genre.objects.create(name=name)
        # success message
        messages.success(request, "Successfully Created")
        return HttpResponseRedirect(genre.get_absolute_url())
    else:
        messages.error(request, "Unsuccessfully Created")
    context = {
        "form" : form,
        "title" : "Create New Genre"
    }
    return render(request, "genre/genre_form.html", context)


def genre_update(request, genre_id = None):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404
    if not request.user.is_authenticated():
        raise Http404

    genre = get_object_or_404(Genre, id=genre_id)
    form = GenreForm(request.POST or None, instance= genre)
    if form.is_valid():
        genre = form.save(commit= False)
        genre.user = request.user
        genre.save()
        # success message
        messages.success(request, "Successfully updated")
        return HttpResponseRedirect(genre.get_absolute_url())
    else:
        messages.error(request, "Unsuccessfully Updated")

    context = {
        "title" : genre.name,
        "genre": genre,
        "form": form
    }
    return render(request, "genre/genre_form.html", context)


def genre_delete(request, genre_id=None ):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404
    if not request.user.is_authenticated():
        raise Http404

    genre = get_object_or_404(Genre, id=genre_id)
    genre.delete()
    messages.success(request, "Successfully deleted")
    return redirect("genres:genre_list")

moopy/templates/genre/genre_detail.html
{% extends 'base.html' %}
{% block title %}Genre Detail{% endblock %}

{% block content %}
    <h1>{{ genre.name }}</h1>
    <i>{{ genre.publish }} - {{ genre.created|timesince }} ago</i><br>
    {% if genre.draft %}<h3>Draft</h3>{% endif %}
    {% if genre.publish > today %}<h3>Future POst</h3>{% endif %}
    {% if genre.user.get_full_name %}

    {% for movie in movies %}
        <h1>{{ movie.title }}</h1>
    {% endfor %}



    Author : <i>{{ genre.user.get_full_name }}</i> <br/>
    {% endif %}

{% endblock %}

moopy/templates/genre/genre_form.html
{% extends 'base.html' %}
{% block title %}Genre Form{% endblock %}

{% block content %}
    <form class="ui form" method="POST" action="">{% csrf_token %}
        {% for field in form %}

          <div class="field">
            <label class="control-label" for="id_{{ field.name }}">{{ field.name }}</label>
            <div class="fields">
                {{ field }}
                <p class="help-text">{{ field.help_text }} </p>
            </div>
          </div>

        {% endfor %}

        <input class="ui blue button" tabindex="0" type="submit" value="Save" />
        <div class="ui orange button" tabindex="0">Cancel</div>
    </form>
{% endblock %}

moopy/templates/genre/genre_list.html
{% extends 'base.html' %}
{% block title %}
{{ title }} | {{ block.super}}
{% endblock %}

{% block content %}
    <div class="ui menu">
      <div class="item">
        <div class="ui action input">
            <form method="GET" action="">
              <input type="text" name="q" placeholder="Search" value="{{ request.get.q }}"/>
              <input class="ui blue button" type="submit" value="Go"/>
            </form>
        </div>
      </div>
          {% if request.user.is_staff or request.user.is_superuser %}
          <div class="right item">
                <a href="{% url 'genres:genre_create' %}" class="fluid ui blue button">New</a>
          </div>
          {% endif %}
    </div>
    <div class="ui segment">
        <div class="ui middle aligned divided list">
            {% for genre in all_genres %}
              <div class="item">
                <div class="right floated content">
                    {% if request.user.is_authenticated and request.user.is_staff or request.user.is_superuser %}
                    <a href="{% url 'genres:genre_update' genre.id %}" class="ui blue basic button">Edit</a>
                    <a href="{% url 'genres:genre_delete' genre.id %}" class="ui blue basic button">Delete</a>
                    {% endif %}
                    <a href="{% url 'movies:movie_list_genre' genre.id %}" class="ui blue basic button">View</a>
                </div>
                <div class="content">
                    <h3>{{ genre.name }}</h3>
                </div>
              </div>
            {% endfor %}
        </div>
    </div>

    <div class="ui pagination menu">
        {% if all_genres.has_previous %}
            <a class="active item" href="?{{ page_request_var }}={{ contacts.previous_page_number }}
            {% if request.get.q %}&q={{ request.get.q }}{% endif %}">
                previous
            </a>
        {% endif %}
        <span class="item">
            Page {{ all_genres.number }} of {{ all_genres.paginator.num_pages }}.
        </span>
        {% if all_genres.has_next %}
            <a class="item" href="?{{ page_request_var }}={{ all_genres.next_page_number }}
            {% if request.get.q %}&q={{ request.get.q }}{% endif %}">
                next
            </a>
        {% endif %}
    </div>
{% endblock %}